---
version: '3'
env:
    ENV: '{{.ENV}}'

vars:
    MODULE: '{{default "default" .MODULE}}'
    EXAMPLE: '{{default "basic" .RECIPE}}'
    VARS: '{{default "config/fixtures.tfvars" .VARS}}'

dotenv: ['.env.{{.ENV}}.aws', '.env.{{.ENV}}.terraform', '.env.{{.ENV}}.terragrunt']

includes:
    common:
        taskfile: ./taskfiles/Taskfile.common.yml
    hooks:
        taskfile: ./taskfiles/Taskfile.precommit.yml
    tf:
        taskfile: ./taskfiles/Taskfile.terraform.yml

tasks:
    default:
        cmds:
            - task: common:default

    hooks-init:
        desc: Initialize and install required hooks
        cmds:
            - task: hooks:hooks-init

    hooks-run:
        desc: Run all the hooks described in the .pre-commit-config.yaml file
        cmds:
            - task: hooks:hooks-run

    tf-module-init:
        desc: Initialize the terraform module
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: 'modules/{{.MODULE}}'}

    tf-module-ci:
        desc: Run CI tasks for the terraform module
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: 'modules/{{.MODULE}}'}
            - task: tf:validate
              vars: {TF_WORKING_DIR: 'modules/{{.MODULE}}'}
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: 'modules/{{.MODULE}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: 'modules/{{.MODULE}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: 'modules/{{.MODULE}}'}
