---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS RDS Cluster Module
    ## Description
    {{ .Header }}
    This module is used to create an AWS RDS Cluster. The current capabilities are supported:
    * 🚀 Create an AWS RDS Cluster
    * 🚀 Create an AWS RDS Cluster Parameter Group
    * 🚀 Create an AWS RDS Cluster Subnet Group

    For more information about this specific resources, please visit its official documentation [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html).
    For more information about the resource configuration using Terraform, please visit the official documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster).

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/rds-cluster/basic/main.tf" }}
    ```

    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}

    ```

    Recipes are included - Some of them are described as follows:
    "Basic configuration" - This recipe is used to create a basic RDS Cluster.
    ```hcl
      {{ include "../../examples/rds-cluster/basic/config/fixtures.tfvars" }}

    ```

    With backup
    ```hcl
      {{ include "../../examples/rds-cluster/basic/config/fixtures-with-backup.tfvars" }}

    ```

    With change management-related configurations
    ```hcl
      {{ include "../../examples/rds-cluster/basic/config/fixtures-with-change-management-config.tfvars" }}

    ```

    With serverless-related configurations (for V1, and V2)
    ```hcl
      {{ include "../../examples/rds-cluster/basic/config/fixtures-with-serverless-config-v1.tfvars" }}

    ```
    ```hcl
      {{ include "../../examples/rds-cluster/basic/config/fixtures-with-serverless-config-v2.tfvars" }}

    ```
    And more. Check the [config](./examples/rds-cluster/basic/config) folder for more examples.


    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
