---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS RDS cluster Security group
    ## Description
    {{ .Header }}
    This module provides a RDS Security group resource in AWS, with out-of-the-box features:
    * 🚀 Allow ingress traffic from a list of CIDR blocks
    * 🚀 Allow ingress traffic from a list of security groups
    * 🚀 Allow outbound traffic to a list of CIDR blocks
    * 🚀 Allow outbound traffic to a list of security groups
    * 🚀 Allow access between Db members of the same cluster

    For more information, please check the [official documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.RDSSecurityGroups.html).

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/rds-cluster-sg/basic/main.tf" }}
    ```

    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
