---
version: '3'

vars:
    TF_MODULE: '{{default "" .TF_MODULE}}'
    TF_EXAMPLE_RECIPE: '{{default "basic" .TF_EXAMPLE_RECIPE}}'
    TF_VARS: '{{default "" .TF_VARS}}'
    TF_BACKEND: '{{default "" .TF_BACKEND}}'

    AWS_ACCESS_KEY_ID: '{{default "" .AWS_ACCESS_KEY_ID}}'
    AWS_SECRET_ACCESS_KEY: '{{default "" .AWS_SECRET_ACCESS_KEY}}'
    AWS_DEFAULT_REGION: '{{default "us-east-1" .AWS_DEFAULT_REGION}}'


includes:
    common:
        taskfile: ./../taskfiles/TaskFile.common.yml

    tf:
        taskfile: ./../taskfiles/TaskFile.terraform.yml

tasks:
    clean:
        desc: Clean all the .terraform directories
        cmds:
            - task: common:clean

    init:
        deps: [clean]
        cmds:
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}'}

    plan:
        deps: [clean]
        cmds:
            - task: tf:plan
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}', TF_VARS_FILE: '{{.TF_VARS}}'}

    apply:
        deps: [clean]
        cmds:
            - task: tf:apply
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}', TF_VARS_FILE: '{{.TF_VARS}}'}


    destroy:
        deps: [clean]
        cmds:
            - task: tf:destroy
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}', TF_VARS_FILE: '{{.TF_VARS}}'}

    ci:
        cmds:
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}'}
            - task: tf:validate
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}'}

    docs:
        deps: [clean]
        cmds:
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TF_MODULE}}/{{.TF_EXAMPLE_RECIPE}}'}
